<?php
$title = t($section) . ' · ' . t('admin');
require ROOT . '/app/Views/header.php';
$flash = $_SESSION['admin_flash'] ?? '';
unset($_SESSION['admin_flash']);
$edit = $edit ?? [];
function adminField(string $name, string $label, string $value = '', string $type = 'text'): void
{
    echo '<label>' . e(t($label)) . '<input name="' . e($name) . '" type="' . e($type) . '" value="' . e($value) . '" autocomplete="off"></label>';
}
function adminSelect(string $name, array $choices, string $selected = ''): void
{
    echo '<select name="' . e($name) . '">';
    foreach ($choices as $key) {
        echo '<option value="' . e($key) . '"' . ($key === $selected ? ' selected' : '') . '>' . e(t($key)) . '</option>';
    }
    echo '</select>';
}
function adminDateTime($value): string
{
    if ($value === null || $value === '') {
        return '—';
    }
    return (new DateTimeImmutable((string) $value, new DateTimeZone('UTC')))
        ->setTimezone(new DateTimeZone('Asia/Bishkek'))
        ->format('d.m.Y H:i:s');
}
?>
<main class="wrap admin-layout"><aside class="panel admin-nav"><h2><?= e(t('admin')) ?></h2><p class="muted"><?= e($admin['login']) ?> · <?= e(t($admin['role'])) ?></p><p class="muted small">UTC+6 · Бишкек</p><nav><?php foreach ($sections as $item): ?><?php if ($admin['role'] === 'super' || !in_array($item, $superOnly, true)): ?><a class="<?= $section === $item ? 'current' : '' ?>" href="<?= e(url('admin/' . $item)) ?>"><?= e(t($item)) ?></a><?php endif; ?><?php endforeach; ?></nav><form method="post"><?= csrfField() ?><input type="hidden" name="action" value="logout"><button class="secondary wide"><?= e(t('logout')) ?></button></form></aside><section class="admin-content"><h1><?= e(t($section)) ?></h1><?php if ($error || $flash): ?><p class="notice <?= $error ? 'danger' : '' ?>" role="alert"><?= e($error ?: $flash) ?></p><?php endif; ?>
<?php if ($section === 'blog'): ?>
    <?php require ROOT . '/app/Views/admin-blog.php'; ?>
<?php elseif ($section === 'logs'): ?>
    <section id="admin-log-console" class="log-console panel" data-feed="<?= e(url('admin/logs')) ?>" data-empty="<?= e(t('logs_empty')) ?>" data-unavailable="<?= e(t('logs_unavailable')) ?>" data-user-labels="<?= e(json_encode(['user_entry' => t('logs_user_entry'), 'user_join' => t('logs_user_join'), 'user_next' => t('logs_user_next'), 'user_leave' => t('logs_user_leave'), 'user_message' => t('logs_user_message'), 'user_report' => t('logs_user_report'), 'user_profile' => t('logs_user_profile'), 'user_forget' => t('logs_user_forget')], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)) ?>" data-timezone="Asia/Bishkek">
        <div class="log-console-toolbar">
            <label><?= e(t('logs_filter')) ?><select id="log-level"><option value="all"><?= e(t('logs_all')) ?></option><option value="success"><?= e(t('logs_success')) ?></option><option value="error"><?= e(t('logs_error')) ?></option><option value="users"><?= e(t('logs_users')) ?></option><option value="audit"><?= e(t('logs_audit')) ?></option></select></label>
            <label><?= e(t('logs_path')) ?><input id="log-search" type="search" maxlength="120" placeholder="/admin, /api/send…"></label>
            <span class="log-live"><i aria-hidden="true"></i> LIVE · UTC+6</span>
        </div>
        <div id="log-output" class="log-output" role="log" aria-live="polite"><p class="log-empty"><?= e(t('logs_loading')) ?></p></div>
    </section>
    <script src="<?= e(url('assets/admin-logs.js')) ?>" defer></script>
<?php elseif ($section === 'dashboard'): ?>
<div class="metric-grid"><?php foreach ($stats as $key => $number): ?><div class="panel metric"><span><?= e(t($key)) ?></span><strong><?= (int) $number ?></strong></div><?php endforeach; ?></div><p class="muted"><?= e(t('registrations_note')) ?></p><div class="panel"><h2><?= e(t('chart')) ?></h2><canvas id="chart" height="240" data-points="<?= e(json_encode($chart)) ?>" aria-label="<?= e(t('chart')) ?>" role="img"></canvas><div class="chart-data"><?php foreach ($chart as $point): ?><span><?= e($point['day']) ?>: <?= (int) $point['n'] ?></span><?php endforeach; ?></div></div><h2><?= e(t('distribution')) ?></h2><div class="metric-grid"><?php foreach (['cities' => $cities, 'gender' => $genders, 'age' => $ages] as $key => $items): ?><div class="panel"><h3><?= e(t($key)) ?></h3><?php foreach ($items as $item): ?><p class="spread"><span><?= e($key === 'gender' ? t($item['label']) : $item['label']) ?></span><b><?= (int) $item['n'] ?></b></p><?php endforeach; ?></div><?php endforeach; ?></div><?php if ($views): ?><div class="panel"><h2><?= e(t('views')) ?></h2><?php foreach ($views as $v): ?><p><?= e(substr($v['name'], 3)) ?>: <?= (int) $v['value'] ?></p><?php endforeach; ?></div><?php endif; ?>
<?php elseif ($section === 'users'): ?>
<form class="panel search-form" method="get"><label><?= e(t('search_label')) ?><input name="q" value="<?= e($query) ?>"></label><button><?= e(t('search')) ?></button></form>
<?php if (!empty($profile)): ?><div class="panel"><h2>#<?= (int) $profile['id'] ?> · <?= e($profile['nickname']) ?></h2><p><?= e(t($profile['gender'])) ?> · <?= (int) $profile['age'] ?> · <?= e($profile['name_' . lang()]) ?></p><p class="small">IP: <?= e($profile['ip_hash'] ? substr($profile['ip_hash'], 0, 16) . '…' : '—') ?><br>ID: <?= e($profile['fingerprint'] ? substr($profile['fingerprint'], 0, 16) . '…' : '—') ?></p><form method="post"><?= csrfField() ?><input type="hidden" name="action" value="ban"><input type="hidden" name="id" value="<?= (int) $profile['id'] ?>"><div class="form-grid"><label><?= e(t('scope')) ?><?php adminSelect('scope', ['session', 'ip', 'fingerprint'], 'session'); ?></label><?php adminField('hours', 'hours', '24', 'number'); ?></div><?php adminField('reason', 'reason'); ?><button class="danger-button"><?= e(t('ban')) ?></button></form></div><?php endif; ?>
<?php elseif ($section === 'reports' && !empty($report)): ?>
<div class="panel"><h2>#<?= (int) $report['id'] ?> · <?= e(t($report['reason'])) ?></h2><p><?= e($report['detail']) ?></p><p><?= e(t($report['status'])) ?> · <?= e(adminDateTime($report['created_at'])) ?> · UTC+6</p><h3><?= e(t('evidence')) ?></h3><?php foreach ($evidence['participants'] ?? [] as $person): ?><p>#<?= (int) $person['session'] ?> <?= e($person['nickname']) ?> · <?= e(t($person['gender'])) ?> · <?= (int) $person['age'] ?> · <?= e($person['city']) ?></p><?php endforeach; ?><div class="evidence"><?php foreach ($evidence['messages'] ?? [] as $message): ?><div class="evidence-line"><small>#<?= (int) $message['sender_id'] ?> · <?= e(adminDateTime($message['created_at'])) ?> · UTC+6</small><p><?= e($message['body']) ?></p></div><?php endforeach; ?><?php if (empty($evidence['messages'])): ?><p><?= e(t('evidence_empty')) ?></p><?php endif; ?></div><?php if ($report['status'] === 'pending'): ?><form method="post"><?= csrfField() ?><input type="hidden" name="id" value="<?= (int) $report['id'] ?>"><?php adminField('hours', 'hours', '24', 'number'); ?><div class="button-row"><button name="action" value="dismiss" class="secondary"><?= e(t('dismiss')) ?></button><button name="action" value="warn"><?= e(t('warn')) ?></button><button name="action" value="ban" class="danger-button"><?= e(t('ban')) ?></button></div></form><?php endif; ?></div>
<?php elseif ($section === 'chats'): ?><div class="panel"><h2><?= e(t('active_chats')) ?>: <?= (int) $active ?></h2><p><?= e(t('archive_note')) ?></p></div>
<?php elseif ($section === 'cities'): ?><form method="post" class="panel"><?= csrfField() ?><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= (int) ($edit['id'] ?? 0) ?>"><?php adminField('name_ru', 'name_ru', $edit['name_ru'] ?? ''); adminField('name_ky', 'name_ky', $edit['name_ky'] ?? ''); ?><label class="check"><input name="enabled" type="checkbox" <?= ($edit['enabled'] ?? 1) ? 'checked' : '' ?>><?= e(t('enabled')) ?></label><button><?= e(t('save')) ?></button></form>
<?php elseif ($section === 'stopwords'): ?><form method="post" class="panel"><?= csrfField() ?><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= (int) ($edit['id'] ?? 0) ?>"><label><?= e(t('kind')) ?><?php adminSelect('kind', ['word', 'link', 'phone', 'messenger'], $edit['kind'] ?? 'word'); ?></label><?php adminField('pattern', 'pattern', $edit['pattern'] ?? ''); ?><label><?= e(t('action')) ?><?php adminSelect('rule_action', ['block', 'replace', 'report'], $edit['action'] ?? 'block'); ?></label><?php adminField('replacement', 'replacement', $edit['replacement'] ?? '***'); ?><label class="check"><input name="enabled" type="checkbox" <?= ($edit['enabled'] ?? 1) ? 'checked' : '' ?>><?= e(t('enabled')) ?></label><button><?= e(t('save')) ?></button></form>
<?php elseif ($section === 'settings'): ?><form method="post" class="panel settings-form"><?= csrfField() ?><input type="hidden" name="action" value="save"><?php foreach (\App\Models\Settings::defaults() as $key => $default): ?><?php if (in_array($key, ['chat_enabled', 'entry_enabled', 'log_messages'], true)): ?><label class="check"><input type="checkbox" name="<?= e($key) ?>" <?= setting($key) === '1' ? 'checked' : '' ?>><?= e(t($key)) ?></label><?php elseif (strpos($key, 'rules_') === 0): ?><label><?= e(t($key)) ?><textarea name="<?= e($key) ?>" rows="6"><?= e(setting($key)) ?></textarea></label><?php elseif ($key === 'language'): ?><label><?= e(t($key)) ?><select name="language"><option value="ru" <?= setting($key) === 'ru' ? 'selected' : '' ?>>Русский</option><option value="ky" <?= setting($key) === 'ky' ? 'selected' : '' ?>>Кыргызча</option></select></label><?php elseif ($key === 'transport'): ?><label><?= e(t($key)) ?><select name="transport"><option value="poll" <?= setting($key) === 'poll' ? 'selected' : '' ?>>Polling</option><option value="long" <?= setting($key) === 'long' ? 'selected' : '' ?>>Long-polling</option></select></label><?php else: ?><?php adminField($key, $key, setting($key), is_numeric($default) ? 'number' : ($key === 'support_email' ? 'email' : 'text')); ?><?php endif; ?><?php endforeach; ?><button><?= e(t('save')) ?></button></form>
<?php elseif ($section === 'admins'): ?><form method="post" class="panel"><?= csrfField() ?><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= (int) ($edit['id'] ?? 0) ?>"><?php adminField('login', 'login', $edit['login'] ?? ''); adminField('email', 'email', $edit['email'] ?? '', 'email'); adminField('password', 'new_password', '', 'password'); ?><label><?= e(t('role')) ?><?php adminSelect('role', ['moderator', 'super'], $edit['role'] ?? 'moderator'); ?></label><label class="check"><input type="checkbox" name="enabled" <?= ($edit['enabled'] ?? 1) ? 'checked' : '' ?>><?= e(t('enabled')) ?></label><?php adminField('current_password', 'current_password', '', 'password'); ?><button><?= e(t('save')) ?></button></form>
<?php elseif ($section === 'security'): ?><div class="panel"><h2>2FA / TOTP</h2><p><?= e(t('2fa_note')) ?></p><?php if (!empty($_SESSION['pending_totp']) && !$admin['totp_secret']): ?><p><code><?= e($_SESSION['pending_totp']) ?></code></p><p class="muted">SHA1 · 6 digits · 30 seconds</p><?php endif; ?><form method="post"><?= csrfField() ?><?php adminField('current_password', 'current_password', '', 'password'); ?><?php if ($admin['totp_secret'] || !empty($_SESSION['pending_totp'])): ?><?php adminField('totp', 'totp'); ?><?php endif; ?><button name="action" value="<?= $admin['totp_secret'] ? 'totp_disable' : (!empty($_SESSION['pending_totp']) ? 'totp_enable' : 'totp_prepare') ?>"><?= e(t($admin['totp_secret'] ? 'totp_disable' : (!empty($_SESSION['pending_totp']) ? 'totp_enable' : 'totp_prepare'))) ?></button></form></div><form method="post" class="panel"><?= csrfField() ?><h2><?= e(t('change_password')) ?></h2><input type="hidden" name="action" value="password"><?php adminField('current_password', 'current_password', '', 'password'); adminField('password', 'new_password', '', 'password'); ?><button><?= e(t('save')) ?></button></form>
<?php elseif ($section === 'backup'): ?>
<div class="panel">
    <p><?= e(t('backup_note')) ?></p>
    <p><?= e(t('backup_schedule_note')) ?></p>
    <p><strong><?= e(t('backup_last_success')) ?>:</strong> <?= !empty($backup['lastSuccess']) ? e(adminDateTime($backup['lastSuccess'])) . ' · UTC+6' : e(t('backup_never')) ?></p>
    <?php if (!empty($backup['error'])): ?><p class="notice danger" role="alert"><?= e(t('backup_error')) ?>: <?= e($backup['error']) ?></p><?php endif; ?>
    <form method="post"><?= csrfField() ?><input type="hidden" name="action" value="create"><?php adminField('current_password', 'current_password', '', 'password'); ?><button><?= e(t('backup_now')) ?></button></form>
    <form method="post"><?= csrfField() ?><input type="hidden" name="action" value="export"><?php adminField('current_password', 'current_password', '', 'password'); ?><button class="secondary"><?= e(t('export')) ?></button></form>
    <form method="post"><?= csrfField() ?><input type="hidden" name="action" value="cleanup"><button class="secondary"><?= e(t('cleanup')) ?></button></form>
</div>
<div class="panel table-wrap"><h2><?= e(t('backup_files')) ?></h2><table><thead><tr><th><?= e(t('file')) ?></th><th><?= e(t('date')) ?></th><th><?= e(t('size')) ?></th><th><?= e(t('action')) ?></th></tr></thead><tbody><?php foreach ($backup['files'] as $file): ?><tr><td><?= e($file['name']) ?></td><td><?= e(adminDateTime($file['modified'])) ?> · UTC+6</td><td><?= e(number_format($file['size'] / 1048576, 2)) ?> MB</td><td><a href="<?= e(url('admin/backup')) ?>?download=<?= e(rawurlencode($file['name'])) ?>"><?= e(t('download')) ?></a></td></tr><?php endforeach; ?><?php if (!$backup['files']): ?><tr><td colspan="4"><?= e(t('empty')) ?></td></tr><?php endif; ?></tbody></table></div>
<?php endif; ?>
<?php if (!in_array($section, ['dashboard', 'settings', 'security', 'backup', 'blog', 'logs'], true)): ?><div class="panel table-wrap"><table><thead><tr><?php foreach (array_keys($rows[0] ?? ['id' => null]) as $column): ?><th><?= e(t($column)) ?></th><?php endforeach; ?><th><?= e(t('action')) ?></th></tr></thead><tbody><?php foreach ($rows as $row): ?><tr><?php foreach ($row as $column => $value): ?><td><?= e(in_array($column, ['last_seen', 'started_at', 'ended_at', 'created_at', 'expires_at', 'revoked_at', 'resolved_at', 'published_at', 'updated_at'], true) ? adminDateTime($value) : (in_array($column, ['reason', 'status', 'role', 'gender', 'kind', 'action'], true) ? t((string) $value) : ($column === 'value' && strlen((string) $value) > 20 ? substr($value, 0, 16) . '…' : $value))) ?></td><?php endforeach; ?><td><?php if (in_array($section, ['users', 'reports', 'cities', 'stopwords', 'admins'], true)): ?><a href="<?= e(url('admin/' . $section)) ?>?id=<?= (int) $row['id'] ?>"><?= e(t('view')) ?></a><?php endif; ?><?php if (($section === 'bans' && !$row['revoked_at']) || $section === 'stopwords'): ?><form method="post"><?= csrfField() ?><input type="hidden" name="id" value="<?= (int) $row['id'] ?>"><button class="text-button" name="action" value="<?= $section === 'bans' ? 'unban' : 'delete' ?>"><?= e(t($section === 'bans' ? 'unban' : 'delete')) ?></button></form><?php endif; ?></td></tr><?php endforeach; ?><?php if (!$rows): ?><tr><td colspan="12"><?= e(t('empty')) ?></td></tr><?php endif; ?></tbody></table></div><nav class="pagination"><a href="?page=<?= max(1, $pageNumber - 1) ?>&amp;q=<?= e(rawurlencode($query ?? '')) ?>"><?= e(t('previous')) ?></a><span><?= e(t('page')) ?> <?= (int) $pageNumber ?></span><?php if (count($rows) === 50): ?><a href="?page=<?= $pageNumber + 1 ?>&amp;q=<?= e(rawurlencode($query ?? '')) ?>"><?= e(t('next')) ?></a><?php endif; ?></nav><?php endif; ?>
</section></main><script src="<?= e(url('assets/admin.js')) ?>" defer></script>
<?php require ROOT . '/app/Views/footer.php'; ?>
